version: '2'

services:
    foo-d-service:
        restart: always
        build: ./foo-d-service/
        volumes:
            - ./data:/data
        links:
            - redis:redis
        depends_on:
            - redis
        working_dir: /usr/src/app
        command: python app.py

    redis:
        restart: always
        image: redis:latest
        ports:
            - "6379:6379"
